#!/usr/bin/env ruby
# backlog - command line interface to backlog management

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require File.expand_path('../../config/environment',  __FILE__)

#require File.expand_path('../../app/models/backlog_rc',  __FILE__)
#require File.expand_path('../../app/models/item',  __FILE__)

puts "Backlog"

if ARGV.empty?
  category = Category.find "epic"
  item = Item.new category, $stdin
  file = item.save
  if file
    puts "Item saved as '#{file}'" 
  else
    puts "Item unchanged"
  end
end
